name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install
        run: flutter pub get

      - name: Change API uri
        env:
          PRODUCTION_API_BASE_URI: ${{ secrets.PRODUCTION_API_BASE_URI }}
        run: |
          uri=$PRODUCTION_API_BASE_URI
          sed -i -e "s!http://localhost:8000/api/v1!$uri!" lib/constants.dart

      - name: Build
        run: flutter build web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.8.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build/web
